// Approval Page Script for Steward Bank (USD)
document.addEventListener('DOMContentLoaded', function() {
    // Get application data
    const applicationData = JSON.parse(sessionStorage.getItem('applicationData') || '{}');
    
    if (!applicationData.loanAmount) {
        console.warn('No application data found, using defaults');
    }
    
    // Get loan details
    const loanAmount = parseFloat(applicationData.loanAmount) || 1000;
    const loanTerm = parseInt(applicationData.loanTerm) || 12;
    const annualRate = 0.12; // 12% APR
    const monthlyRate = annualRate / 12;
    
    // Calculate monthly payment
    const monthlyPayment = loanAmount * monthlyRate * Math.pow(1 + monthlyRate, loanTerm) / 
                          (Math.pow(1 + monthlyRate, loanTerm) - 1);
    
    const totalRepayment = monthlyPayment * loanTerm;
    
    // Update display with USD currency
    const approvedAmountEl = document.getElementById('approvedAmount');
    const loanAmountDetailEl = document.getElementById('loanAmountDetail');
    const monthlyPaymentDetailEl = document.getElementById('monthlyPaymentDetail');
    const repaymentPeriodDetailEl = document.getElementById('repaymentPeriodDetail');
    const totalRepaymentDetailEl = document.getElementById('totalRepaymentDetail');
    
    if (approvedAmountEl) approvedAmountEl.textContent = '$' + loanAmount.toLocaleString();
    if (loanAmountDetailEl) loanAmountDetailEl.textContent = '$' + loanAmount.toLocaleString();
    if (monthlyPaymentDetailEl) monthlyPaymentDetailEl.textContent = '$' + Math.round(monthlyPayment).toLocaleString();
    if (repaymentPeriodDetailEl) repaymentPeriodDetailEl.textContent = loanTerm + ' months';
    if (totalRepaymentDetailEl) totalRepaymentDetailEl.textContent = '$' + Math.round(totalRepayment).toLocaleString();
    
    console.log('Approval page loaded:', {
        loanAmount,
        loanTerm,
        monthlyPayment: Math.round(monthlyPayment),
        totalRepayment: Math.round(totalRepayment)
    });
    
    // Create confetti effect
    createConfetti();
});

// Download agreement function
function downloadAgreement() {
    const applicationData = JSON.parse(sessionStorage.getItem('applicationData') || '{}');
    const loanAmount = parseFloat(applicationData.loanAmount) || 1000;
    const loanTerm = parseInt(applicationData.loanTerm) || 12;
    const annualRate = 0.12;
    const monthlyRate = annualRate / 12;
    
    const monthlyPayment = loanAmount * monthlyRate * Math.pow(1 + monthlyRate, loanTerm) / 
                          (Math.pow(1 + monthlyRate, loanTerm) - 1);
    const totalRepayment = monthlyPayment * loanTerm;
    
    const agreementText = `
LOAN AGREEMENT
==================

Application Number: ${applicationData.applicationId || 'N/A'}
Date: ${new Date().toLocaleDateString('en-US')}

BORROWER INFORMATION:
Name: ${applicationData.fullName || 'N/A'}
Email: ${applicationData.email || 'N/A'}

LOAN DETAILS:
Loan Amount: $${loanAmount.toLocaleString()}
Interest Rate: ${(annualRate * 100)}% APR
Loan Term: ${loanTerm} months
Monthly Payment: $${Math.round(monthlyPayment).toLocaleString()}
Total Repayment: $${Math.round(totalRepayment).toLocaleString()}

PURPOSE: ${applicationData.loanPurpose || 'N/A'}

TERMS AND CONDITIONS:
1. This is a preliminary loan approval document.
2. Final approval is subject to verification of the information you provided.
3. Monthly payments are due on the first of each month.
4. Late fees may apply as per our terms of service.
5. Early repayment is allowed without penalty.

This document is for informational purposes only and is not binding.

Generated by Steward Bank Loan System
    `;
    
    // Create downloadable file
    const blob = new Blob([agreementText], { type: 'text/plain' });
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `loan-agreement-${applicationData.applicationId || 'draft'}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    window.URL.revokeObjectURL(url);
}

// View dashboard function
function viewDashboard() {
    alert('Dashboard feature coming soon! You will be able to track your loan status here.');
}

// Social sharing function
function shareOnSocial(platform) {
    const applicationData = JSON.parse(sessionStorage.getItem('applicationData') || '{}');
    const loanAmount = parseFloat(applicationData.loanAmount) || 1000;
    const text = `I got approved for a $${loanAmount.toLocaleString()} loan with Steward Bank! 🎉`;
    const url = window.location.origin;
    
    let shareUrl = '';
    
    switch(platform.toLowerCase()) {
        case 'twitter':
            shareUrl = `https://twitter.com/intent/tweet?text=${encodeURIComponent(text)}&url=${encodeURIComponent(url)}`;
            break;
        case 'facebook':
            shareUrl = `https://www.facebook.com/sharer/sharer.php?u=${encodeURIComponent(url)}`;
            break;
        case 'linkedin':
            shareUrl = `https://www.linkedin.com/sharing/share-offsite/?url=${encodeURIComponent(url)}`;
            break;
        case 'whatsapp':
            shareUrl = `https://wa.me/?text=${encodeURIComponent(text + ' ' + url)}`;
            break;
    }
    
    if (shareUrl) {
        window.open(shareUrl, '_blank', 'width=600,height=400');
    }
}

// Confetti animation
function createConfetti() {
    const colors = ['#C41E3A', '#10b981', '#FFD700', '#ef4444', '#8b5cf6'];
    const confettiContainer = document.querySelector('.approval-card');
    
    if (!confettiContainer) return;
    
    for (let i = 0; i < 50; i++) {
        setTimeout(() => {
            const confetti = document.createElement('div');
            confetti.style.cssText = `
                position: fixed;
                width: 10px;
                height: 10px;
                background: ${colors[Math.floor(Math.random() * colors.length)]};
                left: ${Math.random() * 100}%;
                top: -10px;
                opacity: ${Math.random()};
                transform: rotate(${Math.random() * 360}deg);
                pointer-events: none;
                z-index: 9999;
            `;
            document.body.appendChild(confetti);
            
            // Animate fall
            let top = -10;
            const speed = Math.random() * 3 + 2;
            const interval = setInterval(() => {
                top += speed;
                confetti.style.top = top + 'px';
                
                if (top > window.innerHeight) {
                    clearInterval(interval);
                    confetti.remove();
                }
            }, 20);
        }, i * 30);
    }
}
